Add methods to judge symmetric and antisymmetric
Kaiser-Yang/matrix-calculation-accelerator pull request #114
Opened 2024-06-04 12:53 UTC by 11231f

* `bool Matrix<ELEMENT_TYPE>::symmetric()`
* `bool Matrix<ELEMENT_TYPE>::antisymmetric()`

See #48, #113.

2024-06-04 13:38 UTC, Kaiser-Yang requested changes

2024-06-04 13:38 UTC, Kaiser-Yang commented on src/include/mca/__mca_internal/single_thread_matrix_calculation.h
>  /* Check whether or not rows of matrix are symmetric
Update this and make it be similar with the pic below:
![image](https://github.com/Kaiser-Yang/matrix-calculation-accelerator/assets/58209855/8868d797-51a3-450e-8a61-d511f9fd7213)

2024-06-04 13:38 UTC, Kaiser-Yang commented on src/include/mca/__mca_internal/single_thread_matrix_calculation.h
>  /* Check whether or not rows of matrix are antisymmetric
Same requirements as the previous one.

2024-06-04 13:38 UTC, Kaiser-Yang commented on src/include/mca/matrix.h
>  // TODO
remove this `TODO`

2024-06-04 13:38 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +    c                  = Matrix<double>(squareShape);
Use random number to generator a symmetric matrix.

2024-06-04 13:38 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +    ASSERT_EQ(singleBool2, multiBool2);
add those:
* `ASSERT_FALSE(singleBool2)`
* `ASSERT_TRUE(singleBool3)`

2024-06-04 13:38 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +    c                  = Matrix<double>(squareShape);
`c` is not an antisymmetrix matrix.

2024-06-04 13:38 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +    ASSERT_EQ(singleBool2, multiBool2);
Make the `c` an antisymmetric matrix and add those:
* `ASSERT_FALSE(singleBool2)`
* `ASSERT_TRUE(singleBool3)`

2024-06-04 13:40 UTC, Kaiser-Yang requested changes

2024-06-04 13:40 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +    // get the multi-thread mode time
You forget to use 'init(THREAD_NUM)` to initialize the `mca`.

2024-06-04 13:40 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +    // get the multi-thread mode time
You forget to use 'init(THREAD_NUM)` to initialize the `mca`.

2024-06-05 11:21 UTC, Kaiser-Yang requested changes

2024-06-05 11:21 UTC, Kaiser-Yang commented on src/include/mca/matrix.h
> +bool Matrix<T>::symmetric() const noexcept {
remove the `noexcept` here and at the declarations.

2024-06-05 11:21 UTC, Kaiser-Yang commented on src/include/mca/matrix.h
> +bool Matrix<T>::antisymmetric() const noexcept {
remove the `noexcept`

2024-06-05 11:21 UTC, Kaiser-Yang commented on src/include/mca/matrix.h
> +   // namespace mca
remove this line

2024-06-05 11:21 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +    for (size_t i = 0; i < a.rows(); i++) {
update `a.rows` with `c.rows` and update `a.columns` with `c.columns`

2024-06-05 11:21 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +    for (size_t i = 0; i < a.rows(); i++) {
update `a` with `c`.

2024-06-05 11:21 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +            if (i < j) (c.get(i, j) = c.get(j, i) = generator() % MAX_VALUE);
add `{}`.

2024-06-05 11:21 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +            if (i < j) (c.get(i, j) = generator() % MAX_VALUE);
add `{}`.

2024-06-05 12:53 UTC, Quentin9922 approved these changes

2024-06-05 13:04 UTC, Kaiser-Yang approved these changes

2024-06-05 13:05 UTC, merged