Add tests for same address
Kaiser-Yang/matrix-calculation-accelerator pull request #67
Opened 2024-05-19 10:11 UTC by luckygalaxy666

Because we remove the constraints for a and output's addresses. They
were required at different addresses in the past, but now they can be at
the same address except in matrix multiplication. Therefore this is a
need to test whether those can work when a and output's addresses are
same. Besides, I've found that transposeSingleThread can not work well
 when a and ouput are at the same address. See #61.

2024-05-19 13:24 UTC, Quentin9922 approved these changes

2024-05-20 01:41 UTC, Kaiser-Yang requested changes

2024-05-20 01:41 UTC, Kaiser-Yang commented on test/src/same_address_test.cpp
> +    Matrix<> result = {{pow(2, 1), pow(2, 2), pow(2, 3)},
Add `#include <cmath>` and use `std::pow`

2024-05-20 02:16 UTC, Quentin9922 approved these changes

2024-05-20 02:18 UTC, Kaiser-Yang approved these changes

2024-05-20 02:18 UTC, merged