Add tests for assignment and constructor
Kaiser-Yang/matrix-calculation-accelerator pull request #78
Opened 2024-05-27 12:31 UTC by luckygalaxy666

Improve the unit rests to cover some parts.
Correct some mistakes about Creating a diag matirx in multithread as well

See #77

2024-05-27 12:52 UTC, Quentin9922 approved these changes

2024-05-27 13:01 UTC, Kaiser-Yang commented
Add periods here:
![image](https://github.com/Kaiser-Yang/matrix-calculation-accelerator/assets/58209855/4073660d-3952-417f-99ef-3cf8134e4dc8)

2024-05-27 13:10 UTC, Kaiser-Yang requested changes

2024-05-27 13:10 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +    Matrix<int> a({{0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
remove this matrix a.

2024-05-27 13:10 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +TEST_F(TestMatrixMultiThread, constructorFromInitializerList) {
rename the unit test with `constructorFromDiag`

2024-05-27 13:10 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +    ASSERT_TRUE(equalSingleThread(a, n1, 0, n1.size()));
remove this.

2024-05-27 13:10 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +    b                  = std::initializer_list<std::initializer_list<double>>{{}, {}};
add an empty line here to make b not align with the next line.

2024-05-27 13:10 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +    ASSERT_EQ(a.shape().columns, 0);
`a.shape()` should be `Shape(0, 0)`.

2024-05-27 13:10 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +    ASSERT_EQ(b.dataPtr(), nullptr);
Check `b.shape()`.

2024-05-28 01:44 UTC, Kaiser-Yang commented
If you'd like them be seperated lines, bullet points are RECOMMENDED:
![image](https://github.com/Kaiser-Yang/matrix-calculation-accelerator/assets/58209855/cddab3c6-ce5f-40b6-8c6a-ccda4c5185de)

2024-05-28 02:01 UTC, Kaiser-Yang approved these changes

2024-05-28 02:02 UTC, merged