Finish some tasks of multi thread.
Kaiser-Yang/matrix-calculation-accelerator pull request #93
Opened 2024-05-30 09:20 UTC by 11231f

These tasks are:
* transpose(a)
* transpose(a,output)
* a.transpose()

 See #48.

2024-05-30 10:49 UTC, Kaiser-Yang commented
The title should not contain any punctuations.

2024-05-30 10:50 UTC, Kaiser-Yang commented
Write the declarations thoroughly:
![image](https://github.com/Kaiser-Yang/matrix-calculation-accelerator/assets/58209855/34a28c88-51b4-4d59-b681-bf88e61631b1)

2024-05-30 11:46 UTC, Quentin9922 requested changes

2024-05-30 11:46 UTC, Quentin9922 commented on src/include/mca.h
> +// TODO
You should delete line of `TODO`

2024-05-30 11:46 UTC, Quentin9922 commented on src/include/mca.h
> +            threadPool().addTask([a, start = i * res.first, len = res.first, &output]() {
In the capture list here, maybe using the `&a` can be better.

2024-05-30 11:46 UTC, Quentin9922 commented on src/include/mca.h
> +// TODO
Delete the line.

2024-05-30 11:46 UTC, Quentin9922 commented on test/src/multi_thread_matrix_test.cpp
> +
Maybe you should initialize the matrix `a`.

2024-05-31 10:33 UTC, Kaiser-Yang commented
![image](https://github.com/Kaiser-Yang/matrix-calculation-accelerator/assets/58209855/aaf9e723-e255-496e-8c3b-16335a48f567)
Update the typo.

2024-05-31 10:57 UTC, Kaiser-Yang requested changes

2024-05-31 10:57 UTC, Kaiser-Yang commented on src/include/matrix.h
>       *       If O and ELEMENT_TYPE are not same, all the elements will first be cast to
This `If O and ELEMTN_TYPE...` should be removed, there is no `O` and `ELEMENT_TYPE` at all.

2024-05-31 10:57 UTC, Kaiser-Yang commented on src/include/matrix.h
> +    Matrix<> output(shape(), 0);
remove the `, 0`. In our new version, `Matrix<> output(shape())` will create a new matrix whose elements are all `ELEMENT_TYPE()`.

2024-05-31 10:57 UTC, Kaiser-Yang commented on src/include/matrix.h
> +    if (threadNum() == 0 || limit() > size()) {
update this will `>=`.

2024-05-31 10:57 UTC, Kaiser-Yang commented on src/include/mca.h
> + *                  [3, 4] */
should be `[3, 4]]` you forget the last `]`.

2024-05-31 10:57 UTC, Kaiser-Yang commented on src/include/mca.h
> +    // single mode
Add `assert(a.rows() == output.colomns())` and `assert(a.columns() == output.rows())`.

2024-05-31 10:57 UTC, Kaiser-Yang commented on src/include/mca.h
> +    if (threadNum() == 0 || limit() > a.size()) {
update with `>=`.

2024-05-31 10:57 UTC, Kaiser-Yang commented on src/include/mca.h
> +void transpose(const Matrix<T> &a, Matrix<O> &output) {
Because you have written this function, your function in `matrix.h` can call this function directly by using `transpose(*this, output)`.

2024-05-31 10:57 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +TEST_F(TestMatrixMultiThread, transpose) {
This file is for testing the methods in `matrix.h`, so the first two unit tests should not be here. They should be moved to `test/src/multi_thread_matrix_calculation_test.cpp`.

2024-05-31 10:57 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +    singleOutput = multiOutput = Matrix<>(squareShape);
For transposition, you should use a shape that is not a square one.

2024-05-31 10:57 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +    singleOutput = multiOutput = Matrix<>(squareShape);
Use a shape that is not square.

2024-05-31 10:57 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +    Matrix<> a(squareShape);
Use a non-square shape.

2024-05-31 10:57 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +TEST_F(TestMatrixMultiThread, selfTranspose) {
This should be update with `transpose`.

2024-05-31 10:57 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +TEST_F(TestMatrixMultiThread, transpose) {
This should be updated with `transposeMatrix`

2024-05-31 10:57 UTC, Kaiser-Yang commented on test/src/multi_thread_matrix_test.cpp
> +TEST_F(TestMatrixMultiThread, transposeToOutput) {
This should be updated with `transposeMatrixToOutput`.

2024-05-31 10:57 UTC, Kaiser-Yang commented on src/include/mca.h
> +    if (threadNum() == 0 || limit() > a.size()) {
update with `>=`.

2024-05-31 10:57 UTC, Kaiser-Yang commented on src/include/mca.h
> + *                       [3, 4] */
should be `[3, 4]]` you forget the last `]`.

2024-05-31 10:57 UTC, Kaiser-Yang commented on src/include/matrix.h
> +
Add `// TODO` here, this is not finished yet.

2024-05-31 11:03 UTC, Kaiser-Yang requested changes

2024-05-31 11:03 UTC, Kaiser-Yang commented on src/include/mca.h
> +    Matrix<T> output(a.shape());
After transpositon, `output`'s shape shoule be `Shape{a.columns(), a.rows()}` rather than `a.shape()`.

2024-05-31 11:06 UTC, Kaiser-Yang requested changes

2024-05-31 11:06 UTC, Kaiser-Yang commented on src/include/matrix.h
> +    Matrix<> output(shape(), 0);
After transpositon, `output'`s shape shoule be `Shape{columns(), rows()}` rather than `shape()`.

2024-05-31 13:38 UTC, Kaiser-Yang approved these changes

2024-05-31 13:54 UTC, Quentin9922 approved these changes

2024-05-31 13:54 UTC, merged